# This workflow will do a clean install of node dependencies and run `npm start` every morning

name: Node.js CI

on:
    schedule:
        - cron: '10 8 * * *'
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [10.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm start
        env:
            CI: true
            GIST_ID: 'fbd1743e56040c69bb06b8846fa731d0'
            MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
            MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
